---

- name: "Get Ansible to give you an inventory!"
  hosts: localhost
  gather_facts: False
  tasks:

#  - raw: ls /etc/*release > /tmp/junk
#  - raw: echo "" >>/tmp/junk
#  - raw: cat /etc/*release >> /tmp/junk
#  - raw: echo "" >>/tmp/junk
#  - raw: echo "whoami=`whoami`" >> /tmp/junk
#  - raw: which jq > /tmp/junk
#  - raw: hostname > /tmp/junk
#  - raw: ls -la /usr/bin/jq >> /tmp/junk
  - raw: /etc/ansible/hosts >>/tmp/junk
  - raw: cat /tmp/junk
    register: clc_var

  - debug: var=clc_var.stdout

#  - name: "Install inventory script"
#    copy:
#      src: files/inventory/inventory.sh
#      dest: /var/tmp/inventory.sh
#      owner: root
#      group: root
#      mode: 0744
#
#  - name: Install the latest version of jq
#    yum: name=jq state=latest
#
#  - name: Run inventory script.  Save output as /var/tmp/inventory.csv
#    raw: /var/tmp/inventory.sh > /var/tmp/inventory.csv
#
#- name: "Copy inventory file to UC1JMT1ANSIBL02!"
#  hosts: UC1JMT1ANSIBL02
#  gather_facts: False
#  tasks:
#
#  - name: "Install inventory script"
#    copy:
#      src: /var/tmp/inventory.sh
#      dest: /var/tmp/inventory.sh
#      owner: root
#      group: root
#      mode: 0644
